/// Flutter icons Abi_socios
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Abi_socios
///      fonts:
///       - asset: fonts/Abi_socios.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Abi_socios {
  Abi_socios._();

  static const _kFontFam = 'Abi_socios';
  static const String? _kFontPkg = null;

  static const IconData camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eventos_icono = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_icono = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filtro_icono = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData galeria_icono = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guardardatos_icono = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburguesa_icono = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_icono = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_icono = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_icono = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_icono = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData misdatos_icono = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData networking_icono = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData revista_icono = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tarjeta_icono = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verpresentacion_icono = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website_icono = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp_icono = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_icono = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agenda_icono = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agregar = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beneficio_icono = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campanita = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casita = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData configuracion_icono = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contrasena = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData descargarpresentacion_icono = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editardatos_icono = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emergencia_icono = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terminosycondiciones_icono = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
